services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: simplyfile-app:latest
    ports:
      - "9091:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: simplyfile
      POSTGRES_DB: simplyfile

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.6
    environment:
      REDIS_PASSWORD: 123456

volumes:
  postgres-data:

networks:
    default:
        name: simplyfile-network