spring.datasource.url=jdbc:postgresql://localhost:5432/simplyfile
spring.datasource.username=simplyfile
spring.datasource.password=123456
spring.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

storage.path=./storage